import { createReducer } from '@reduxjs/toolkit';
import initialState from './initialState';
import {
  getContact,
  addContact,
  deleteContact,
  updateContact,
  editFavoriteContact,
  deleteAvatarContact,
} from './contacts/contacts-operations';
import {
  registerUser,
  logInUser,
  logOutUser,
  currentUser,
  updateUser,
  deleteAvatarUser,
} from './auth/auth-operations';

export const loadingReducer = createReducer(initialState.loading, {
  [getContact.pending.type]: () => true,
  [getContact.fulfilled.type]: () => false,
  [getContact.rejected.type]: () => false,
  [addContact.pending.type]: () => true,
  [addContact.fulfilled.type]: () => false,
  [addContact.rejected.type]: () => false,
  [deleteContact.pending.type]: () => true,
  [deleteContact.fulfilled.type]: () => false,
  [deleteContact.rejected.type]: () => false,
  [updateContact.pending.type]: () => true,
  [updateContact.fulfilled.type]: () => false,
  [updateContact.rejected.type]: () => false,
  [editFavoriteContact.pending.type]: () => true,
  [editFavoriteContact.fulfilled.type]: () => false,
  [editFavoriteContact.rejected.type]: () => false,
  [deleteAvatarContact.pending.type]: () => true,
  [deleteAvatarContact.fulfilled.type]: () => false,
  [deleteAvatarContact.rejected.type]: () => false,
  [registerUser.pending.type]: () => true,
  [registerUser.fulfilled.type]: () => false,
  [registerUser.rejected.type]: () => false,
  [logInUser.pending.type]: () => true,
  [logInUser.fulfilled.type]: () => false,
  [logInUser.rejected.type]: () => false,
  [logOutUser.pending.type]: () => true,
  [logOutUser.fulfilled.type]: () => false,
  [logOutUser.rejected.type]: () => false,
  [currentUser.pending.type]: () => true,
  [currentUser.fulfilled.type]: () => false,
  [currentUser.rejected.type]: () => false,
  [updateUser.pending.type]: () => true,
  [updateUser.fulfilled.type]: () => false,
  [updateUser.rejected.type]: () => false,
  [deleteAvatarUser.pending.type]: () => true,
  [deleteAvatarUser.fulfilled.type]: () => false,
  [deleteAvatarUser.rejected.type]: () => false,
});
